<DEFINE :STAMPER (DIR)
  #DECL( (DIR F) STRING (C) <OR FALSE CHANNEL> (I VALUE) FIX )
	<SET F <STRING .DIR ";DSK:STAMP >">>
	<RENAME .F TO .F>
	<SET C <OPEN "READ" .F>>
	<SET I <PARSE <8 .C>>>
	<CLOSE .C>
	.I>
